### ISSUE TITLE
New Relic causes error

### ISSUE THREAD

**Issue by rexmadden** [dtaniwaki/rack-dev-mark#32]
I installed new_relic in dev mode, and this happened. Goes away when I remove new_relic and/or dev_mark

```
Puma caught this error: undefined method `bytesize' for #<Rack::DevMark::Middleware:0x007fd5e78621e8> (NoMethodError)
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/rack-dev-mark-0.7.4/lib/rack/dev-mark/middleware.rb:36:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/railties-5.0.0.beta4/lib/rails/rack/logger.rb:36:in `call_app'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/railties-5.0.0.beta4/lib/rails/rack/logger.rb:24:in `block in call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/activesupport-5.0.0.beta4/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/activesupport-5.0.0.beta4/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/activesupport-5.0.0.beta4/lib/active_support/tagged_logging.rb:70:in `tagged'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/railties-5.0.0.beta4/lib/rails/rack/logger.rb:24:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/actionpack-5.0.0.beta4/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/rack-2.0.0.alpha/lib/rack/method_override.rb:22:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/rack-2.0.0.alpha/lib/rack/runtime.rb:22:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/activesupport-5.0.0.beta4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/actionpack-5.0.0.beta4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/actionpack-5.0.0.beta4/lib/action_dispatch/middleware/static.rb:136:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/rack-2.0.0.alpha/lib/rack/sendfile.rb:111:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/railties-5.0.0.beta4/lib/rails/engine.rb:522:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/newrelic_rpm-3.15.2.317/lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/puma-3.4.0/lib/puma/configuration.rb:224:in `call'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/puma-3.4.0/lib/puma/server.rb:569:in `handle_request'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/puma-3.4.0/lib/puma/server.rb:406:in `process_client'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/puma-3.4.0/lib/puma/server.rb:271:in `block in run'
/Users/rexmadden/.rvm/gems/ruby-2.3.0@the_sting/gems/puma-3.4.0/lib/puma/thread_pool.rb:114:in `block in spawn_thread'
```

**Comment by dtaniwaki** [comment]
Hi @rexmadden Sorry for not replying this for a long time. I think https://github.com/dtaniwaki/rack-dev-mark/pull/33 fixes this problem.
